name: Aditi Gupta Design
favicon: null
layout_spectrum: 0
typography_spectrum: 0.50358
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#e9c4b2'
    - '#231c16'
    - '#744b30'
    - '#7f7576'
    - '#af8876'
  brandStrength: 0.5
  lightness: 0.544474242022261
  saturation: 0.8314214868005365
  rhythmicContrast: 0.6685922350734472
purpose: []
