name: Aditi Gupta Design
favicon: null
layout_spectrum: 0
typography_spectrum: 0.50358
title: ' Aditi Gupta Design is a luxury Residential Interior Design Firm'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fad0b7'
    - '#dfac91'
    - '#a98d82'
    - '#efe9d3'
    - '#6b4e26'
  brandStrength: 0.4375
  lightness: 0.875
  saturation: 0.8314214868005365
  rhythmicContrast: 0.6685922350734472
purpose: []
